# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(141614)
$foreground = rgb(FFF7E1)
$color0 = rgb(3B3D3B)
$color1 = rgb(589D15)
$color2 = rgb(ED5F1A)
$color3 = rgb(FB8516)
$color4 = rgb(FC922A)
$color5 = rgb(FDD99A)
$color6 = rgb(FFE8A8)
$color7 = rgb(F6EBCB)
$color8 = rgb(ADA58E)
$color9 = rgb(589D15)
$color10 = rgb(ED5F1A)
$color11 = rgb(FB8516)
$color12 = rgb(FC922A)
$color13 = rgb(FDD99A)
$color14 = rgb(FFE8A8)
$color15 = rgb(F6EBCB)
