# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(111111)
$foreground = rgb(FFF8DA)
$color0 = rgb(393939)
$color1 = rgb(51464B)
$color2 = rgb(994734)
$color3 = rgb(AC493E)
$color4 = rgb(B8463E)
$color5 = rgb(827155)
$color6 = rgb(BFB070)
$color7 = rgb(F6ECC2)
$color8 = rgb(ACA588)
$color9 = rgb(6C5D64)
$color10 = rgb(CD5F45)
$color11 = rgb(E56153)
$color12 = rgb(F55E52)
$color13 = rgb(AD9672)
$color14 = rgb(FEEA96)
$color15 = rgb(F6ECC2)
