# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(111113)
$foreground = rgb(F4E9D3)
$color0 = rgb(393A3B)
$color1 = rgb(9166AF)
$color2 = rgb(5E8268)
$color3 = rgb(567CB0)
$color4 = rgb(567CB0)
$color5 = rgb(8C8B93)
$color6 = rgb(A79162)
$color7 = rgb(E6D7B8)
$color8 = rgb(A19781)
$color9 = rgb(C288E9)
$color10 = rgb(7EAD8B)
$color11 = rgb(72A6EA)
$color12 = rgb(72A6EA)
$color13 = rgb(BAB9C4)
$color14 = rgb(DFC182)
$color15 = rgb(E6D7B8)
